name: Data Preprocessing

on:
  push:
    branches:
      - main

jobs:
  preprocessing:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          python -m pip install -r requirements.txt

      - name: Run preprocessing
        run: |
          python main.py

      - name: Upload results
        uses: actions/upload-artifact@v2
        with:
          name: results
          path: data/cleaned
